### ISSUE TITLE
Error "JSON parse command" after pressing the "shutdown"-button

### ISSUE THREAD

**Issue by Kunibert-007** [instalator/ioBroker.synology#19]
I get this error in the iobroker-log after pressing the "shutdown"-button:

`

synology.0 | 2018-10-08 22:44:10.398 | error | Error JSON parse command {}
-- | -- | -- | --

`

I have a Synology Diskstation 916+.

Best regards

**Comment by instalator** [comment]
Reinstall driver

**Comment by Kunibert-007** [comment]
What do you mean with reinstall driver? You mean the adapter in ioBroker? I installed it freshly yesterday...

**Comment by instalator** [comment]
version 0.0.4?



С уважением,
ВладимирKunibert-007 <notifications@github.com> | От: 10 окт. 2018 г. 2:30 ДП | Сообщение:What do you mean with reinstall driver? You mean the adapter in ioBroker? I installed it freshly yesterday...

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/instalator/ioBroker.synology","title":"instalator/ioBroker.synology","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/instalator/ioBroker.synology"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kunibert-007 in #19: What do you mean with reinstall driver? You mean the adapter in ioBroker? I installed it freshly yesterday..."}],"action":{"name":"View Issue","url":"https://github.com/instalator/ioBroker.synology/issues/19#issuecomment-428320970"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/instalator/ioBroker.synology/issues/19#issuecomment-428320970",
"url": "https://github.com/instalator/ioBroker.synology/issues/19#issuecomment-428320970",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [instalator/ioBroker.synology] Error \"JSON parse command\" after pressing the \"shutdown\"-button (#19)",
"sections": [
{
"text": "",
"activityTitle": "**Kunibert-007**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Kunibert-007",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"instalator/ioBroker.synology\",\n\"issueId\": 19,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"instalator/ioBroker.synology\",\n\"issueId\": 19\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/instalator/ioBroker.synology/issues/19#issuecomment-428320970"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 389455152\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by instalator** [comment]
Vetsion 0.0.4?

**Comment by AFPass** [comment]
Hi, i have the same error.
Synology Adapter Version 0.0.4
DSM 6.2.1-23824 Update 1

**Comment by xatrix78** [comment]
same error

**Comment by yeli69** [comment]
Same Error ...

- Linux ioBroker 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
- node/nodejs v8.16.0
- ioBroker.admin 3.6.3
- Adapter Version 0.0.4
- DS1511+ with DSM 6.2.2-24922 Update 2

**Comment by latzi0710** [comment]
Hi, i have the same error on pressing reboot or shutdown.
Configuration:
Synology Adapter Version 0.0.4
DSM-Version: DSM 6.2.2-24922 Update 4

**Comment by instalator** [comment]
> Hi, i have the same error on pressing reboot or shutdown.
> Configuration:
> Synology Adapter Version 0.0.4
> DSM-Version: DSM 6.2.2-24922 Update 4

Update from github
