### ISSUE TITLE
error: synology.0 ***DEBUG RES ERR : code(119) "119"

### ISSUE THREAD

**Issue by Apollon77** [instalator/ioBroker.synology#4]
I get this error in logs from time to time ... mostly 1time directly after each otrher, sometimes more often.

Is it maybe that the "pull intervall" is too high? How ofter data are pulled? Can this be configured?

**Comment by arteck** [comment]
same problem here

**Comment by Apollon77** [comment]
I also got a memory problem some time with my DS213+ (maybe they have a memory leak somewhere?). System halted because of memory full.
I currently disabled the adapter because I think he is the reason for that ... 

I now switch to a 716+, so will try again :-))

**Comment by instalator** [comment]
Keep in touch with events

**Comment by integer63** [comment]
I have two different Synology stations and get this error for both after a short time after starting the Instance. Both Instances turn from "green" to "yellow".

**Comment by Apollon77** [comment]
BTW: I now checked memory usage on my new DS716+II ... synocgid is using slowly more and more memory ... yesterday 98MB, today we ware at 179MB ... it seems that there is a memory leak which is caused by the continous adapter requests.
Can you check on your systems too?

**Comment by Apollon77** [comment]
two days agi synocgid crashed (segfault according to log) and so Web-UI of Sysnology was unrachable ... needed to reboot on the machine :-(
Anyone else such problems :-(

**Comment by Kunibert-007** [comment]
Same problem here

**Comment by DutchmanNL** [comment]
I can conform this issue, after having the adapter running for several days i noticed my web interface of sinology was nog reachable anymore. Message : You cannot login because there is no disk space available. The message is incorrect as my system still has 1TB + available but i noticed my root partition was full.

At the same time the adapter provided me the error messages :
`

2018-05-18 09:38:52.315 - error: synology.0 ***DEBUG RES ERR : code(100) "100"
--
2018-05-18 09:38:52.316 - error: synology.0 ***DEBUG RES ERR : code(999) ""
2018-05-18 09:38:52.517 - debug: synology.0 ---DEBUG RES DATA--- :{"api": dsm, "method": getInfo }
RESPONSE: ""

`

My synology runs smoothly without having the adapter activated, if i activate him again the system crash with same issue after 3 or 4 days.
Would be very glad if we can find the root cause of this issue as the adapter itself provides great information about the healthy of my system.

Thank you !

**Comment by JPfeiffer66** [comment]
The same problems with the synocgid on a DS 916+, 8 GB RAM with DSM 6.2.2.-24922 Update 2.

**Comment by Apollon77** [comment]
One issue I found was that /temp runs full ... can this be?

**Comment by Ilovegym66** [comment]
Yes, If temp ist full, you cant Login to the Diskstation any more..

**Comment by Quentame** [comment]
It seems the issue is coming from the session_id passed by GET and if starts by a number, passing via a cookie seems to solve the issue.

Seen on : aerialls/synology-srm#3

In [ProtoThis/python-synology](https://github.com/ProtoThis/python-synology) we create a new session and login again to get a right session_id, should be handled better, but working.

**Comment by Apollon77** [comment]
@instalator could you please adjust?! For many users the adapter is not usable right now.

**Comment by instalator** [comment]
> @instalator could you please adjust?! For many users the adapter is not usable right now.

I will try to update the adapter in the near future.

**Comment by instalator** [comment]
> @instalator could you please adjust?! For many users the adapter is not usable right now.

Tell me where to look at the memory filling?

**Comment by Apollon77** [comment]
When I remember correctly it was visible in the synology process explorer and one these cgi processes was using more and more ram ...

**Comment by instalator** [comment]
> When I remember correctly it was visible in the synology process explorer and one these cgi processes was using more and more ram ...

I updated the npm version of the package and the API version. Over the past day, I did not see an increase in memory consumption. Please help in checking. My version DSM 6.2-23739

**Comment by Apollon77** [comment]
GitHub Version? or did you update on NPM?

**Comment by instalator** [comment]
> GitHub Version
+

**Comment by instalator** [comment]
I launched 2 instances, the memory is on the same level.
![image](https://user-images.githubusercontent.com/11523624/79841149-30edea00-83e1-11ea-94da-3cc30cea7d7a.png)

**Comment by instalator** [comment]
There seems to be a problem.
![image](https://user-images.githubusercontent.com/11523624/79881860-f35a8280-841b-11ea-8356-73baa0cff5a7.png)

**Comment by instalator** [comment]
> GitHub Version? or did you update on NPM?

New version from github in 12 hours. Please check.
![image](https://user-images.githubusercontent.com/11523624/79933340-fa17e280-8479-11ea-92d7-b6d21725fb33.png)

**Comment by instalator** [comment]
fixed
