### ISSUE TITLE
Security Issue: Access data are not encrypted

### ISSUE THREAD

**Issue by Azathoth88** [instalator/ioBroker.synology#64]
Derzeit werden die Zugangsdaten unverschlüsselt in der Datenbank bzw. objects.json gespeichert.
Das ist ein erhebliches Sicherheitsrisiko. Im Synology Forum wurde nun mehrfach berichtet, dass das NAS kompromittiert und verschlüsselt wurde. Dass Kennwörter unverschlüsselt gespeichert werden ist schon seit Jahren nicht state of the art. Bitte die daher die Zugangsdaten (Benutzer + Kennwort) verschlüsseln.

Translation:
---
Currently, the access data is stored unencrypted in the database or objects.json.
This is a considerable security risk. There have been several reports in the Synology forum that the NAS has been compromised and encrypted. The fact that passwords are stored unencrypted has not been state of the art for years. Please therefore encrypt the access data (user + password).

**Comment by Azathoth88** [comment]
Bitte dringend prüfen, ansonsten kann man derzeit von der Verwendung des Adapters nur abraten! Das Kennwort ist in der objects.json in Klartext!

**Comment by instalator** [comment]
Вас никто не заставляет его использовать. Все объекты хранятся в object.json такова логика работы Iobroker

**Comment by Azathoth88** [comment]
Based on the unencrypted data, Synology systems were taken over and encrypted. I know of several cases from the Synology forum. The access data in the objects.json should be encrypted, as is the case with other adapters - or do you support hackers?

**Comment by instalator** [comment]
I am not an iobroker developer, you need to contact the developer @Bluefox

**Comment by Azathoth88** [comment]
I think not. You are registered here as the owner and developer of the Synology adapter. So I don't see why I would need to contact bluefox. Who stores the password in plain text? Your adapter or ioBroker?

**Comment by instalator** [comment]
those. do you just need to store the password in object .json encrypted? In this case, the decryption keys will be in cleartext in the code of the dapetra itself, does it bother? If not, I will wait for a pull request.

**Comment by MC-1984** [comment]
Any news about the issue? @Azathoth88: Can you please clarify if you mean that in general other NAS have been compromised or was this specific iobroker adapter used to gain access to the NAS? If the adapter was used the adapter should be removed and all users warned immediately.

**Comment by MC-1984** [comment]
Maybe this could help: https://forum.iobroker.net/topic/42934/adapter-passwort-entschlüsseln

Apparently, if you know what you do, it is fairly simple to encrypt the password.

**Comment by instalator** [comment]
> Maybe this could help: [https://forum.iobroker.net/topic/42934/adapter-passwort-entschlüsseln](https://forum.iobroker.net/topic/42934/adapter-passwort-entschl%C3%BCsseln)
> 
> Apparently, if you know what you do, it is fairly simple to encrypt the password.

How can this protect if the decryption algorithm is publicly available? Anyone can access it and decrypt the password.

**Comment by Apollon77** [comment]
@instalator Yes this is true basically, but new adapters are required to encrypt access passwords/credentials because we at least want to have kind of a basic security here. So if "already-in-repo" adapters also adjust it this would be best!

So, IF you have access to the system on the host (ssh) or full API access to read all objects or you have admin access to the admin then anyone with a bit of knowledge can find a way to decrypt the encrypted password. Right.

But it is still industry best practice to NOT store or transport unencrypted passwords and so we try to get at least a bit of security into that part. And we achieve this here.

Starting with js-controller 3.0 you even do not need to code any line you can just configure the fields that are encrypted in io-package and done. But yes this needs requiring js-controller 3.0+ and admin 4.0.9+ and is a breaking change for an adater, but honestly i would say it is worth it.

**Comment by Apollon77** [comment]
@Azathoth88 but also one question from me. YOu tell about caes where a NAS was taken over because the data were stored unencrypted in objects.json. So tell me how an attacker got to that data? They should be available on a specific host in the filesystem ... so the hacker had hacked that system too ... While I do not want to "talk away the risk": If dsomeone managed to break into a server then honestly these guys ave bigger issues then just an encrypted NAS ...

**Comment by Apollon77** [comment]
I prepare a PR

**Comment by instalator** [comment]
Check on version 1.0.0

**Comment by MC-1984** [comment]
I cannot check if the password is stored encrypted but I installed version 1.0.0 and I did not run into any issues so far. Thank you very much!
